# Copyright (c) 2018, 2018 IBM Corp. and others
#
# This program and the accompanying materials are made available under
# the terms of the Eclipse Public License 2.0 which accompanies this
# distribution and is available at https://www.eclipse.org/legal/epl-2.0/
# or the Apache License, Version 2.0 which accompanies this distribution and
# is available at https://www.apache.org/licenses/LICENSE-2.0.
#
# This Source Code may also be made available under the following
# Secondary Licenses when the conditions for such availability set
# forth in the Eclipse Public License, v. 2.0 are satisfied: GNU
# General Public License, version 2 with the GNU Classpath
# Exception [1] and GNU General Public License, version 2 with the
# OpenJDK Assembly Exception [2].
#
# [1] https://www.gnu.org/software/classpath/license.html
# [2] http://openjdk.java.net/legal/assembly-exception.html
#
# SPDX-License-Identifier: EPL-2.0 OR Apache-2.0
#

# Dockerfile used for creating a container capable to run AcmeAir monolithic
# Must be running on the same network as the mongodb container
FROM open-liberty:webProfile7

# For consistency with other servers, probably not actually needed
USER root

COPY j2sdk-image-hotspot /opt/openjdk/java
COPY server_hotspot.xml /config/server.xml
COPY mongo.properties /config/mongo.properties
COPY acmeair-webapp-2.0.0-SNAPSHOT.war /config/apps
ENV ACMEAIR_PROPERTIES=/config/mongo.properties

ENV JAVA_HOME="/opt/openjdk/java"
